module:
  hugoVersion:
    extended: true
    min: "0.82" #keep increasing as hugo is upgraded locally
  # imports:
  #   - path: github.com/twbs/icons
  #     ignoreConfig: true
  #     mounts:
  #     - source: icons
  #       target: assets/icons/bootstrap 
  #   - path: github.com/FortAwesome/Font-Awesome
  #     mounts:
  #     - source: svgs
  #       target: assets/icons/awesome
  #   - path: github.com/feathericons/feather
  #     mounts:
  #     - source: icons
  #       target: assets/icons/feather
  #   - path: github.com/simple-icons/simple-icons
  #     mounts:
  #     - source: icons
  #       target: assets/icons/simple
